name: model_code_generator
description: A model code generator project.

publish_to: 'none'

version: 0.0.13+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 9.0.0-nullsafety
  # https://pub.dev/packages/http
  http: 0.13.0
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 2.0.4
  # https://pub.dev/packages/google_fonts
  google_fonts: 2.0.0
  # https://github.com/edufolly/folly_fields
  folly_fields:
    git:
      url: git://github.com/edufolly/folly_fields.git
      ref: v0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/version.txt