name: model_code_generator
description: A new project.

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 8.11.0
  # https://pub.dev/packages/http
  http: 0.12.2
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 0.5.12+4
  # https://pub.dev/packages/google_fonts
  google_fonts: 1.1.1
  # https://github.com/edufolly/folly_fields
  folly_fields:
#     path: ../folly_fields
    git:
      url: git://github.com/edufolly/folly_fields.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
