name: model_code_generator
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: |
          version=$(grep 'version:' pubspec.yaml | cut -c 10-)
          printf "%s" "$version" >assets/version.txt
      - run: flutter build web
      - run: |
          cd build/web
          sed -i 's#<base href="/">#<base href="/model_code_generator/">#g' index.html
          sed -i "s/main.dart.js/main.dart.js?v=$GITHUB_RUN_NUMBER/g" index.html
          git init
          git config --global user.email edufolly@gmail.com
          git config --global user.name "Eduardo Folly"
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/edufolly/model_code_generator.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Publishing the static page ($GITHUB_RUN_NUMBER)."
          git push origin gh-pages -f
